### ISSUE TITLE
Реализовать класс Admin c помощью методологии TDD

### ISSUE THREAD

**Issue by skhomchenko** [levelp/BankWebApp#22]
Пользователь системы с административными, расширенными функциями.

**Comment by Vyacheslav01** [comment]
по классу Admin: видимо, не имеет смысл создавать для этого пользователя отдельный класс.
Можно создать экземпляр из класса User. Каких-то новых полей и методов, дополняющих класс User, я не вижу сейчас.

**Comment by skhomchenko** [comment]
Хорошо
