### ISSUE TITLE
Добавить в класс User новые поля: boolean enabled и String userRole.

### ISSUE THREAD

**Issue by Vyacheslav01** [levelp/BankWebApp#23]
поле boolean enabled имеет два значения: true & false. Выставление значения в true позволит пользователю приложения (админу и клиенту) авторизоваться. Значение поля false запретит клиенту авторизоваться в системе (он не удаляется из БД). В функции системы "удалить клиента" можно реализовать такой способ запрета авторизации.

поле String userRole. 
оно может иметь два значения: role_admin & role_user. role_admin наделяет пользователя системы адиминистративными правами. role_user - это клиент банка.

**Comment by Vyacheslav01** [comment]
+ Аннотации @Column для этих новых полей.

**Comment by skhomchenko** [comment]
userRole возможно лучше сделать int, чтобы завести enum. Который в последствии можно расширять ролями.

**Comment by skhomchenko** [comment]
Предложение поле enabled переименовать в isBlocked если есть потом возможность его восстановить. То есть он потом снова может заходить в систему. если не этот смысл, то назвать isDeleted. И добавить поле isBlocked. Например, блокируется клиент по каким-то причинам.

**Comment by Vyacheslav01** [comment]
про enabled.
идея была такой: в системе должна быть функция удаления клиента из приложения. на самом деле клиент остается в базе (как и в реальности, как я думаю), но ему запрещено авторизовываться в системе. Батон в форме можно подписать "Удалить", а поле в классе лучше так не именовать. как назвать поле - это дело вкуса) либо "позволить", либо "блокировать").
пусть будет isBlocked. а в описании операции можно уточнять: заблокирован по каким-то причинам, либо якобы удален.
Такое-же поле, видимо, нужно добавить и в классе BankAccount. счета клиента тоже нужно удалять/добавлять.

**Comment by Vyacheslav01** [comment]
по userRole. может остановиться на двух ролях?

**Comment by skhomchenko** [comment]
Согласен в BankAccount можно такой функционал добавить. 
Название да можно дать любое главное, чтобы смысл отображало. 
Да, конечно, ролей будет всего две. Я писал с расчетом на расширение)). В целом можно оставить и string.

**Comment by Vyacheslav01** [comment]
в конце концов в класс добавлены поля: boolean isBlocked и String userRole
