### ISSUE TITLE
Реализовать AddressController

### ISSUE THREAD

**Issue by Vyacheslav01** [levelp/BankWebApp#27]

**Comment by Vyacheslav01** [comment]
в этом контроллере URL запроса будет "мапиться" на методы по следующей схеме:
AddressController ---> /address/
/address/add.jsp ---> add()
/address/delete.jsp ---> delete()
/address/update.jsp ---> update()
/address/list.jsp ---> list()

**Comment by skhomchenko** [comment]
В целом не вижу смысла все это делать. так как адреса привязаны к клиенту то и будут добавляться, удаляться, редактироваться вместе с клиентом.

**Comment by skhomchenko** [comment]
Опять же кто будет забивать все адреса всего города, страны и т.д. для этого есть уже готовые справочники типа кладр или другое.

**Comment by Vyacheslav01** [comment]
canceled
