### ISSUE TITLE
Реализовать BankAccountController

### ISSUE THREAD

**Issue by Vyacheslav01** [levelp/BankWebApp#28]

**Comment by Vyacheslav01** [comment]
в этом контроллере URL запроса будет "мапиться" на методы по следующей схеме:
BankAccountController ---> /bankaccount/
/bankaccount/add.jsp ---> add()
/bankaccount/delete.jsp ---> delete()
/bankaccount/update.jsp ---> update()
/bankaccount/list.jsp ---> list()

**Comment by skhomchenko** [comment]
опять же, такая же история, что и с адресом. нет особого смысла в отдельных страницах. Скорее всего будет логика по созданию счета. редактировать его нельзя. Для удаления тоже будет своя логика , которая будет вызываться при удалении клиента. список, может быть есть смысл сделать, но например в деталях или "личном кабинете" клиента будут выводиться все его счета. так что скорее всего отдельной страницы для этого не будет.

**Comment by Vyacheslav01** [comment]
Сергей, у одного клиента может быть несколько счетов. поэтому можно удалять счета, не удаляя при этом клиента из системы.

**Comment by Vyacheslav01** [comment]
canceled
