### ISSUE TITLE
Реализовать TransactionController

### ISSUE THREAD

**Issue by Vyacheslav01** [levelp/BankWebApp#29]

**Comment by Vyacheslav01** [comment]
в этом контроллере URL запроса будет "мапиться" на методы по следующей схеме:
TransactionController ---> /transaction/
/transaction/add.jsp ---> add() // создать новую транзакцию (или добавить транзакцию)
/transaction/delete.jsp ---> delete(int id) // удалить транзакцию с номером id
/transaction/update.jsp ---> update() // обновить транзакцию
/transaction/getTransaction.jsp ---> getTransaction(int id) // получить транзакцию с номером id
/transaction/getTransactions.jsp ---> getTransactions(int clientId) // получить транзакции для клиента с номером clientId

**Comment by skhomchenko** [comment]
Добавления транзакции не будет. Ведь такой странице не будет. удаление(отмена) транзакции будет. Будет список транзакций клиента. Возможно еще страница детализации транзакции.

**Comment by Vyacheslav01** [comment]
согласен, страницу добавления (создания) транзакции не будет. возможно и обновление транзакции следует убрать. тогда остаются: "удалить транзакцию с номером id", "получить инфо о транзакции с номером id", "список всех транзакций клиента".

**Comment by skhomchenko** [comment]
Реализовано.
